
version: '2.1'
services:
  #docker-compose build image
  image:
    build:
      context: .
      dockerfile: Dockerfile
      args:


      - IMAGE_ARG_ENCODING=${IMAGE_ARG_ENCODING:-UTF-8}
      - IMAGE_ARG_JAVA_OPTS=${IMAGE_ARG_JAVA_OPTS}
      - IMAGE_ARG_LANGUAGE=${IMAGE_ARG_LANGUAGE:-en}
      - IMAGE_ARG_LOCALE=${IMAGE_ARG_LOCALE:-en_US}
      - IMAGE_ARG_REGION=${IMAGE_ARG_REGION:-US}
      - IMAGE_ARG_JAVA_HOME=${IMAGE_ARG_JAVA_HOME:-/usr/lib/jvm/java-11-openjdk-amd64}
#      - IMAGE_ARG_JAVA_HOME=${IMAGE_ARG_JAVA_HOME:-/usr/lib/jvm/java-1.8.0-openjdk}
      - IMAGE_ARG_JRE_HOME=${IMAGE_ARG_JRE_HOME:-/usr/lib/jvm/java-11-openjdk-amd64/jre}
#      - IMAGE_ARG_JRE_HOME=${IMAGE_ARG_JRE_HOME:-/usr/lib/jvm/java-1.8.0-openjdk/jre}
      - IMAGE_ARG_JAVA_VENDOR=${IMAGE_ARG_JAVA_VENDOR:-openjdk}
      - IMAGE_ARG_TZ_AREA=${IMAGE_ARG_TZ_AREA:-Etc}
      - IMAGE_ARG_TZ_ZONE=${IMAGE_ARG_TZ_ZONE:-UTC}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-service-base-image-java}:${IMAGE_TAG:-openjdk-11.0.2-en_US.UTF-8_Etc.UTC-centos}
