
FROM cirepo/nix:2.2.1-centos-7.6




ARG IMAGE_ARG_ENCODING
ARG IMAGE_ARG_JAVA_HOME
ARG IMAGE_ARG_JRE_HOME
ARG IMAGE_ARG_JAVA_OPTS
ARG IMAGE_ARG_JAVA_VENDOR
ARG IMAGE_ARG_LANGUAGE
ARG IMAGE_ARG_LOCALE
ARG IMAGE_ARG_REGION
ARG IMAGE_ARG_TZ_AREA
ARG IMAGE_ARG_TZ_ZONE


#COPY --from=cirepo/locale:%IMAGE_ARG_LOCALE%.%IMAGE_ARG_ENCODING%_%IMAGE_ARG_TZ_AREA%.%IMAGE_ARG_TZ_ZONE%-centos-archive /data/root /
COPY --from=cirepo/waitforit:2.4.1-archive /data/root /

COPY --from=cirepo/java-11-%IMAGE_ARG_JAVA_VENDOR%:%IMAGE_ARG_JAVA_VERSION%-alpine-3.9-archive /data/root /
COPY --from=cirepo/java-accessories:latest-archive /data/root /


#echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf


#ENV JAVA_HOME ${IMAGE_ARG_JAVA_HOME:-/usr/lib/jvm/java-1.8.0-openjdk}
ENV JAVA_HOME ${IMAGE_ARG_JAVA_HOME:-/usr/lib/jvm/java-11-openjdk-amd64}
#ENV JRE_HOME ${IMAGE_ARG_JRE_HOME:-/usr/lib/jvm/java-1.8.0-openjdk/jre}
ENV JRE_HOME ${IMAGE_ARG_JRE_HOME:-/usr/lib/jvm/java-11-openjdk-amd64/jre}
ENV JAVA_OPTS -Duser.language=${IMAGE_ARG_LANGUAGE:-en} -Duser.region=${IMAGE_ARG_REGION:-US} -Dfile.encoding=${IMAGE_ARG_ENCODING:-UTF-8} -Duser.timezone=${IMAGE_ARG_TZ_AREA:-Etc}/${IMAGE_ARG_TZ_ZONE:-UTC} ${IMAGE_ARG_JAVA_OPTS}


ENV PATH ${JAVA_HOME}/bin:${PATH}


COPY --chown=centos:centos docker /


USER root
ENV HOME=/root \
    USER=root
RUN set -eux \
  && chown -R root:root /root \
  && yum --enablerepo=base-debuginfo -y update \
#  && yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel \
  && yum -y clean all \
  && BIN_DIR=/usr/bin \
  && MAN_DIR=/usr/share/man/man1 \
  && cd ${BIN_DIR} && find ${JAVA_HOME}/bin -type f -perm -a=x -exec ln -s {} . \; \
  && mkdir -p ${MAN_DIR} \
  && if [[ -d ${JAVA_HOME}/man/man1 ]]; then \
         cd ${MAN_DIR} && find ${JAVA_HOME}/man/man1 -type f -name "*.1" -exec ln -s {} . \;; \
     fi \
  \
# https://github.com/docker-library/openjdk/issues/212#issuecomment-420979840
# https://openjdk.java.net/jeps/341
  && java -Xshare:dump \
  \
# basic smoke test
  && java -version \
  && javac -version
# Install lsof telnet and Arthas, see: https://alibaba.github.io/arthas/as.sh
ENV CLASSPATH .:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib
RUN set -eux \
  && yum -y install telnet lsof \
  && ln -s /opt/jprofiler11 /opt/jprofiler \
  && mkdir -p /usr/local/arthas \
  && cd /usr/local/arthas \
  && curl -L https://alibaba.github.io/arthas/install.sh | sh \
#  && ln -s /opt/perf-map-agent-alpine-3.9_amd64 /opt/perf-map-agent
  && rm -rf /opt/perf-map-agent-alpine-3.9_amd64 \
  && mkdir -p /root/.arthas/lib/3.1.0 \
  && ln -s /opt/arthas-3.1.0 /root/.arthas/lib/3.1.0/arthas \
  && mkdir -p /home/centos/.arthas/lib/3.1.0 \
  && ln -s /opt/arthas-3.1.0 /home/centos/.arthas/lib/3.1.0/arthas \
  && cd /opt \
  && yum -y install "perl(open)" \
  && git clone --depth=1 https://github.com/brendangregg/FlameGraph \
# provide symbols
  && yum -y install glibc iptables \
  && yum --enablerepo=base-debuginfo --nogpgcheck -y install glibc-debuginfo iptables-debuginfo kernel-debuginfo-$(uname -r) \
  && yum -y autoremove \
  && yum -y clean all
ENV PATH ${PATH}:/usr/local/arthas


# setup for systemd containers
ENV container docker

# Install minimal pcp (i.e. pcp-conf) and it's dependencies, clean the cache.
# This is intended as the base image for all other PCP containers. The
# bintray repo is enabled by default, see comments above.
#
# pcp-3.12.2
#
#
#
#
#
#
RUN set -eux \
  && yum --showduplicates list pcp \
  && yum -y install createrepo.noarch \
  && yum -y install pcp pcp-devel pcp-conf pcp-webapi perf redhat-rpm-config \
  && yum --nogpgcheck -y install parfait-examples pcp-parfait-agent \
  && mkdir -p /var/lib/pcp && chmod -R 777 /var/lib/pcp \
  && yum clean all

# Run in the container as root - avoids host/container user mismatches
ENV PCP_USER root
ENV PCP_GROUP root

# Register pmcd as a service to be started by systemd
RUN set -eux \
  && systemctl enable pmcd \
  && systemctl enable pmwebd \
  && systemctl enable pmlogger
#  && systemctl disable pmcd \
#  && systemctl disable pmwebd \
#  && systemctl disable pmlogger
#  && systemctl restart pmcd \
#  && systemctl restart pmwebd \
#  && systemctl restart pmlogger

# PCP_PMDAS_DIR=/var/lib/pcp/pmdas
# https://github.com/spiermar/vector-pmda
ENV FLAMEGRAPH_DIR /opt/FlameGraph
ENV PERF_RECORD_SECONDS 30
ENV PCP_PMDAS_DIR /var/lib/pcp/pmdas
RUN set -eux \
  && git clone https://github.com/jvm-profiling-tools/perf-map-agent.git /usr/lib/jvm/perf-map-agent-openjdk \
  && yum -y install git make \
  && yum -y install cmake3 gcc gcc-c++ \
  && cd /usr/lib/jvm/perf-map-agent-openjdk \
  && cmake3 . \
  && make \
  && bin/create-links-in /usr/local/bin \
  && git clone -b pcp4 https://github.com/infra-top/vector-pmda.git /var/lib/pcp/pmdas/vector \
  && cd /var/lib/pcp/pmdas/vector \
  && make \
# Can not mount volumes
# '--tmpfs=/run --tmpfs=/tmp --volume=/run/containers/pcp-java-app-centos:/run/pcp --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
# while building images.
# Need to run `Install` in a running container.
# systemctl restart pmcd; cd /var/lib/pcp/pmdas/vector; echo -e 'b\n' | ./Install
  && yum -y remove cmake3 gcc gcc-c++ \
  && yum clean all

# Setup pmcd to run in unprivileged mode of operation
RUN . /etc/pcp.conf; \
    rm -f $PCP_SYSCONFIG_DIR/pmcd; \
    echo "PMCD_ROOT_AGENT=0" >> $PCP_SYSCONFIG_DIR/pmcd

# Configure pmcd with a minimal set of DSO agents
RUN . /etc/pcp.conf; \
    rm -f $PCP_PMCDCONF_PATH; \
    echo "# Name  ID  IPC  IPC Params  File/Cmd" >> $PCP_PMCDCONF_PATH; \
    echo "pmcd     2  dso  pmcd_init   $PCP_PMDAS_DIR/pmcd/pmda_pmcd.so"   >> $PCP_PMCDCONF_PATH; \
    echo "proc     3  dso  proc_init   $PCP_PMDAS_DIR/proc/pmda_proc.so"   >> $PCP_PMCDCONF_PATH; \
    echo "linux   60  dso  linux_init  $PCP_PMDAS_DIR/linux/pmda_linux.so" >> $PCP_PMCDCONF_PATH; \
    echo "mmv     70  dso  mmv_init    $PCP_PMDAS_DIR/mmv/pmda_mmv.so"     >> $PCP_PMCDCONF_PATH; \
    rm -f $PCP_VAR_DIR/pmns/root_xfs $PCP_VAR_DIR/pmns/root_jbd2 $PCP_VAR_DIR/pmns/root_root; \
    touch $PCP_VAR_DIR/pmns/.NeedRebuild

# Disable service advertising - no avahi support in the container
# (dodges warnings from pmcd attempting to connect during startup)
RUN . /etc/pcp.conf && echo "-A" >> $PCP_PMCDOPTIONS_PATH

# allow unauthenticated access to proc.* metrics (default is false)
ENV PROC_ACCESS 1

# Expose pmcd's main port on the host interface
EXPOSE 44321
EXPOSE 44323

STOPSIGNAL SIGRTMIN+3


RUN set -ex \
  && find ${HOME} -name '*.sh' -maxdepth 1 -exec chmod 0755 {} \; \
  && mkdir -p ${HOME}/data


VOLUME ["${HOME}/data", "/tmp"]


RUN systemctl enable entrypoint


USER root
WORKDIR /root
CMD ["/sbin/init"]
