
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - develop
  - master

dist: trusty
env:
  global:
  - IMAGE_ARG_ALPINE_MIRROR=dl-cdn.alpinelinux.org
  # In java11 modules java.xml.bind, java.xml.ws and java.xml.ws.annotation are absent.
  #- IMAGE_ARG_JAVA_OPTS="--add-modules=ALL-SYSTEM"
  matrix:
  - OS_DIST=alpine IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
  - OS_DIST=alpine IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu

  - OS_DIST=alpine IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
  - OS_DIST=alpine IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu

  - OS_DIST=alpine IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_LOCALE=zh_CN IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
  - OS_DIST=alpine IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_LOCALE=zh_CN IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu

  - OS_DIST=alpine IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_LOCALE=zh_CN IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
  - OS_DIST=alpine IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_LOCALE=zh_CN IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu


  - OS_DIST=centos IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
#  - OS_DIST=centos IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu
  - OS_DIST=centos IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_LOCALE=zh_CN IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk

  - OS_DIST=fedora IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
#  - OS_DIST=fedora IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu
  - OS_DIST=fedora IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_LOCALE=zh_CN IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk

  - OS_DIST=ubuntu IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
#  - OS_DIST=ubuntu IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_LOCALE=en_US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu
  - OS_DIST=ubuntu IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_LOCALE=zh_CN IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk


group: edge
#install: true

#before_script:
script:
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash build.sh
- kill %1
#after_script:

services:
- docker
sudo: required
