
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - develop
  - master

dist: trusty
env:
  global:
  - IMAGE_ARG_ALPINE_MIRROR=dl-cdn.alpinelinux.org
  - IMAGE_ARG_JAVA_OPTS="--add-modules java.xml.bind,java.xml.ws,java.xml.ws.annotation"
  matrix:
  - IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
  - IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu

  - IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
  - IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=en IMAGE_ARG_REGION=US IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu

  - IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
  - IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_TZ_AREA=Etc  IMAGE_ARG_TZ_ZONE=UTC      IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu

  - IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=openjdk
  - IMAGE_ARG_ENCODING=UTF-8 IMAGE_ARG_LANGUAGE=zh IMAGE_ARG_REGION=CN IMAGE_ARG_TZ_AREA=Asia IMAGE_ARG_TZ_ZONE=Shanghai IMAGE_ARG_JAVA_HOME=/usr/lib/jvm/zulu-11               IMAGE_ARG_JAVA_VERSION=11.0.2 IMAGE_ARG_JAVA_VENDOR=zulu

group: edge
#install: true

#before_script:
script:
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash build.sh
- kill %1
#after_script:

services:
- docker
sudo: required
